CREATE SCHEMA IF NOT EXISTS ZOMATO.AI;
CREATE TABLE IF NOT EXISTS ZOMATO.AI.REVIEW_ENRICHED
(
    REVIEW_ID STRING,
    SENTIMENT_LABEL STRING,
    SENTIMENT_SCORE FLOAT,
    TOPIC STRING,
    KEY_ISSUE STRING,
    MODEL STRING,
    ENRICHED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_REVIEW_ENRICHED
        PRIMARY KEY (REVIEW_ID)
);