USE ROLE ACCOUNTADMIN;
CREATE TABLE IF NOT EXISTS ZOMATO.AI.RAG_INDEX_STATE
(
    REVIEW_ID STRING,
    CONTENT_HASH STRING,
    INDEX_VERSION STRING,
    INDEXED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);