USE ROLE ACCOUNTADMIN;

-- Compute: extra-small, auto-suspend fast so the trial credits last.
CREATE WAREHOUSE IF NOT EXISTS ZOMATO_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + medallion schemas.
CREATE DATABASE IF NOT EXISTS ZOMATO;
CREATE SCHEMA  IF NOT EXISTS ZOMATO.BRONZE;    -- Iceberg tables Spark wrote (dbt sources)
CREATE SCHEMA  IF NOT EXISTS ZOMATO.RAW;       -- only used by the COPY fallback path
CREATE SCHEMA  IF NOT EXISTS ZOMATO.STAGING;   -- cleaned / conformed (dbt)
CREATE SCHEMA  IF NOT EXISTS ZOMATO.MARTS;     -- Gold, Iceberg (dbt)
CREATE SCHEMA  IF NOT EXISTS ZOMATO.SNAPSHOTS; -- SCD2 history (dbt)
CREATE SCHEMA  IF NOT EXISTS ZOMATO.AI;        -- LLM-enriched tables (OpenAI jobs)

-- A role dbt/Airflow will use.
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE   ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT ALL     ON DATABASE  ZOMATO    TO ROLE DBT_ROLE;
GRANT ALL     ON ALL SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE TABLES IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE VIEWS  IN DATABASE ZOMATO TO ROLE DBT_ROLE;

-- A role for the LLM to query the data mart.
CREATE ROLE IF NOT EXISTS TEXT_TO_SQL_ROLE;
GRANT USAGE ON WAREHOUSE ZOMATO_WH TO ROLE TEXT_TO_SQL_ROLE;
GRANT USAGE ON DATABASE ZOMATO TO ROLE TEXT_TO_SQL_ROLE;
GRANT USAGE ON SCHEMA ZOMATO.MARTS TO ROLE TEXT_TO_SQL_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ZOMATO.MARTS TO ROLE TEXT_TO_SQL_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ZOMATO.MARTS TO ROLE TEXT_TO_SQL_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ZOMATO.MARTS TO ROLE TEXT_TO_SQL_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ZOMATO.MARTS TO ROLE TEXT_TO_SQL_ROLE;

--login use the role .
SET my_user = CURRENT_USER();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($my_user);

SELECT 'setup complete' AS status;